module.exports = {
      ADD_NEWUSER: "ADD_NEWUSER",
      CHECK_USERNAME: "CHECK_USERNAME",
      CHANGE_STATE: "CHANGE_STATE",
      LOGIN: "LOGIN",
      RECEIVE_RESULTLOGIN: "RECEIVE_RESULTLOGIN",
      ISLOGIN: "ISLOGIN",
      LOGOUT: "LOGOUT",
      SET_USERNAME: "SET_USERNAME",
      VIEW_ALL_JOURNEYS: "VIEW_ALL_JOURNEYS"
}
