module.exports = {
      RECEIVE_DATA: "RECEIVE_DATA",
      GET_IMAGES: "GET_IMAGES",
      RECEIVE_IMAGES: "RECEIVE_IMAGES",
      GET_IMAGE: "GET_IMAGE",
      RECEIVE_IMAGE: "RECEIVE_IMAGE",
      GET_COMMENT: "GET_COMMENT",
      RECEIVE_COMMENT: "RECEIVE_COMMENT"
}
